spring.application.name=Travel Agency System
spring.profiles.active=dev
app.bootstrap-admin.email=admin@travel.com
app.bootstrap-admin.password=ChangeMe123!
app.bootstrap-admin.first-name=System
app.bootstrap-admin.last-name=Admin